DROP DATABASE IF EXISTS todo;
DROP ROLE IF EXISTS todo;

CREATE USER todo WITH PASSWORD 'todo';
CREATE DATABASE todo;

\connect todo;

CREATE TABLE todos (
	id SERIAL PRIMARY KEY,

	text VARCHAR,
	completed BOOLEAN
);

GRANT ALL PRIVILEGES ON DATABASE todo TO todo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO todo;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO todo;
